version: "3"
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  service:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - mongo
    command: --mongoHost=mongo --mongoDatabase=library --mongoCollection=books

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: library
